using System;
using System.Collections.Generic;
using System.Collections;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Magus.Items
{
    class ItemManager
    {
        private const int MAX_ITEMS = 90;
        public string name, kind, requires;
        public int weight, icon, value, price;
        public List<ItemManager> items = new List<ItemManager>();
        ArrayList items;

        ItemManager()
        {
            name = this.name;
            kind = this.kind;
            weight = this.weight;
            requires = this.requires;
            icon = this.icon;
            value = this.value;
            price = this.price;
            FillList();
            items = new ArrayList();
        }

        ItemManager(string itemName, string itemKind, int itemWeight,
            string itemRequires, int itemIcon, int itemValue, int itemPrice)
        public void AddItem(Item item)
        {
            name = itemName;
            kind = itemKind;
            weight = itemWeight;
            requires = itemRequires;
            icon = itemIcon;
            value = itemValue;
            price = itemPrice;

            items.Add(item);
        }


        public void FillList()
        {
            ItemManager manager = new ItemManager("Sword", "O_CLASS_WEAPON", 4, "O_REQ_ONEHAND", 76, 9, 20);
            items.Add(manager);
            manager = new ItemManager("2H-Sword", "O_CLASS_WEAPON", 8, "O_REQ_TWOHANDS", 74, 15, 75);
            items.Add(manager);
            manager = new ItemManager("Axe", "O_CLASS_WEAPON", 5, "O_REQ_ONEHAND", 85, 10, 20);
            items.Add(manager);
            manager = new ItemManager("Dagger", "O_CLASS_MIXEDWEAPON", 1, "O_REQ_ONEHAND", 88, 6, 10);
            items.Add(manager);
            manager = new ItemManager("Bow", "O_CLASS_RANGEDWEAPON", 3, "O_REQ_TWOHANDS", 83, 9, 20);
            items.Add(manager);
            manager = new ItemManager("Crossbow", "O_CLASS_RANGEDWEAPON", 4, "O_REQ_TWOHANDS", 82, 12, 20);
            items.Add(manager);
            manager = new ItemManager("Throwing star", "O_CLASS_THROWINGWEAPON", 1, "O_REQ_ONEHAND", 89, 9, 5);
            items.Add(manager);
            manager = new ItemManager("Fireblade", "O_CLASS_SPECIAL", 2, "O_REQ_ONEHAND", 173, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Helmet", "O_CLASS_ARMOR", 3, "O_REQ_HEAD", 91, 2, 20);
            items.Add(manager);
            manager = new ItemManager("Shield", "O_CLASS_ARMOR", 3, "O_REQ_ONEHAND", 78, 4, 20);
            items.Add(manager);
            manager = new ItemManager("Leather", "O_CLASS_ARMOR", 3, "O_REQ_BODY", 79, 2, 20);
            items.Add(manager);
            manager = new ItemManager("Armour", "O_CLASS_ARMOR", 7, "O_REQ_BODY", 80, 6, 75);
            items.Add(manager);
            manager = new ItemManager("Emerald", "O_CLASS_GADGET", 1, "O_REQ_NECK", 81, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Emerald ring", "O_CLASS_GADGET", 0, "O_REQ_FINGER", 90, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Arrows", "O_CLASS_ARROWS", 0, "O_REQ_NOTHING", 84, 0, 10);
            items.Add(manager);
            manager = new ItemManager("Studded leather", "O_CLASS_ARMOR", 4, "O_REQ_BODY", 77, 3, 20);
            items.Add(manager);
            manager = new ItemManager("Lightning bolt", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 55, 10, 0);
            items.Add(manager);
            manager = new ItemManager("FireBall", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 60, 5, 0);
            items.Add(manager);
            manager = new ItemManager("Portal", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 56, 7, 0);
            items.Add(manager);
            manager = new ItemManager("Air", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 72, 7, 0);
            items.Add(manager);
            manager = new ItemManager("Fire", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 70, 10, 0);
            items.Add(manager);
            manager = new ItemManager("Water", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 68, 8, 0);
            items.Add(manager);
            manager = new ItemManager("Water", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 68, 8, 0);
            items.Add(manager);
            manager = new ItemManager("Earth", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 67, 8, 0);
            items.Add(manager);
            manager = new ItemManager("Skeleton", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 64, 15, 0);
            items.Add(manager);
            manager = new ItemManager("Zombie", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 65, 15, 0);
            items.Add(manager);
            manager = new ItemManager("Vision", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 69, 2, 0);
            items.Add(manager);
            manager = new ItemManager("Phantom", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 73, 3, 0);
            items.Add(manager);
            manager = new ItemManager("Sleep", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 59, 8, 0);
            items.Add(manager);
            manager = new ItemManager("Slayer", "O_CLASS_WEAPON", 8, "O_REQ_TWOHANDS", 122, 17, 150);
            items.Add(manager);
            manager = new ItemManager("FastFeet", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 54, 8, 0);
            items.Add(manager);
            manager = new ItemManager("Heal", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 53, 5, 20);
            items.Add(manager);
            manager = new ItemManager("StoneAxe", "O_CLASS_WEAPON", 10, "O_REQ_TWOHANDS", 107, 15, 0);
            items.Add(manager);
            manager = new ItemManager("Gloves", "O_CLASS_ARMOR", 1, "O_REQ_HANDS", 58, 1, 20);
            items.Add(manager);
            manager = new ItemManager("Darkness", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 57, 10, 0);
            items.Add(manager);
            manager = new ItemManager("Darkness", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 57, 10, 0);
            items.Add(manager);
            manager = new ItemManager("Sabre", "O_CLASS_WEAPON", 7, "O_REQ_ONEHAND", 86, 10, 0);
            items.Add(manager);
            manager = new ItemManager("Staff", "O_CLASS_WEAPON", 3, "O_REQ_TWOHANDS", 87, 8, 20);
            items.Add(manager);
            manager = new ItemManager("Chaos", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 66, 20, 0);
            items.Add(manager);
            manager = new ItemManager("Demon", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 63, 25, 0);
            items.Add(manager);
            manager = new ItemManager("Cloak", "O_CLASS_ARMOR", 1, "O_REQ_SHOULDERS", 94, 1, 20);
            items.Add(manager);
            manager = new ItemManager("Big shield", "O_CLASS_ARMOR", 6, "O_REQ_ONEHAND", 110, 6, 20);
            items.Add(manager);
            manager = new ItemManager("Big helmet", "O_CLASS_ARMOR", 4, "O_REQ_HEAD", 111, 3, 20);
            items.Add(manager);
            manager = new ItemManager("Opal ring", "O_CLASS_GADGET", 0, "O_REQ_FINGER", 97, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Club", "O_CLASS_WEAPON", 5, "O_REQ_ONEHAND", 119, 11, 20);
            items.Add(manager);
            manager = new ItemManager("Topaz", "O_CLASS_GADGET", 1, "O_REQ_NECK", 123, 0, 300);
            items.Add(manager);
            manager = new ItemManager("Opal", "O_CLASS_GADGET", 1, "O_REQ_NECK", 124, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Stonefoot", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 129, 6, 0);
            items.Add(manager);
            manager = new ItemManager("Lightning", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 71, 15, 0);
            items.Add(manager);
            manager = new ItemManager("DragonTooth", "O_CLASS_WEAPON", 4, "O_REQ_ONEHAND", 132, 13, 150);
            items.Add(manager);
            manager = new ItemManager("Sun's Edge", "O_CLASS_WEAPON", 5, "O_REQ_ONEHAND", 133, 13, 150);
            items.Add(manager);
            manager = new ItemManager("SilverBow", "O_CLASS_RANGEDWEAPON", 3, "O_REQ_TWOHANDS", 134, 11, 100);
            items.Add(manager);
            manager = new ItemManager("Bubble", "O_CLASS_TRINKET", 0, "O_REQ_NOTHING", 92, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Faithful", "O_CLASS_ARROWS", 0, "O_REQ_NOTHING", 142, 0, 50);
            items.Add(manager);
            manager = new ItemManager("SunBow", "O_CLASS_SPECIAL", 3, "O_REQ_TWOHANDS", 150, 11, 150);
            items.Add(manager);
            manager = new ItemManager("Chock", "O_CLASS_SPECIAL", 4, "O_REQ_ONEHAND", 143, 2, 150);
            items.Add(manager);
            manager = new ItemManager("BloodTaste", "O_CLASS_WEAPON", 9, "O_REQ_TWOHANDS", 144, 19, 200);
            items.Add(manager);
            manager = new ItemManager("SunArmour", "O_CLASS_ARMOR", 4, "O_REQ_BODY", 149, 6, 150);
            items.Add(manager);
            manager = new ItemManager("Elven cloak", "O_CLASS_ARMOR", 1, "O_REQ_SHOULDERS", 147, 3, 50);
            items.Add(manager);
            manager = new ItemManager("Focus", "O_CLASS_GADGET", 1, "O_REQ_HANDS", 146, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Terror", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 153, 7, 0);
            items.Add(manager);
            manager = new ItemManager("Berzerk", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 152, 3, 0);
            items.Add(manager);
            manager = new ItemManager("Protection", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 151, 2, 0);
            items.Add(manager);
            manager = new ItemManager("Leadball", "O_CLASS_THROWINGWEAPON", 1, "O_REQ_ONEHAND", 145, 8, 10);
            items.Add(manager);
            manager = new ItemManager("Wooden shield", "O_CLASS_ARMOR", 2, "O_REQ_ONEHAND", 163, 3, 10);
            items.Add(manager);
            manager = new ItemManager("Wakizashi", "O_CLASS_WEAPON", 2, "O_REQ_ONEHAND", 164, 9, 20);
            items.Add(manager);
            manager = new ItemManager("SunHelmet", "O_CLASS_ARMOR", 2, "O_REQ_HEAD", 157, 3, 70);
            items.Add(manager);
            manager = new ItemManager("SunShield", "O_CLASS_ARMOR", 3, "O_REQ_ONEHAND", 158, 6, 70);
            items.Add(manager);
            manager = new ItemManager("ThunderStorm", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 159, 25, 0);
            items.Add(manager);
            manager = new ItemManager("HyperSpace", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 160, 20, 0);
            items.Add(manager);
            manager = new ItemManager("Panic", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 161, 20, 0);
            items.Add(manager);
            manager = new ItemManager("Shooting star", "O_CLASS_SPECIAL", 0, "O_REQ_ONEHAND", 162, 0, 300);
            items.Add(manager);
            manager = new ItemManager("Inferno", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 165, 12, 0);
            items.Add(manager);
            manager = new ItemManager("Negator", "O_CLASS_TRINKET", 3, "O_REQ_NOTHING", 114, 0, 150);
            items.Add(manager);
            manager = new ItemManager("Chain'n'ball", "O_CLASS_WEAPON", 5, "O_REQ_TWOHANDS", 170, 10, 0);
            items.Add(manager);
            manager = new ItemManager("SunGloves", "O_CLASS_ARMOR", 1, "O_REQ_HANDS", 171, 2, 20);
            items.Add(manager);
            manager = new ItemManager("Delay", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 172, 2, 0);
            items.Add(manager);
            manager = new ItemManager("Ghostblade", "O_CLASS_SPECIAL", 4, "O_REQ_ONEHAND", 140, 9, 150);
            items.Add(manager);
            manager = new ItemManager("Enchant", "O_CLASS_SPECIAL", 0, "O_REQ_ONEHAND", 178, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Purify", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 179, 20, 0);
            items.Add(manager);
            manager = new ItemManager("Blue", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Green", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Yellow", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Brown", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Red", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Grey", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("White", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Purple", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            manager = new ItemManager("Black", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100);
            items.Add(manager);
            AddItem(new Item("Sword", "O_CLASS_WEAPON", 4, "O_REQ_ONEHAND", 76, 9, 20));
            AddItem(new Item("2H-Sword", "O_CLASS_WEAPON", 8, "O_REQ_TWOHANDS", 74, 15, 75));
            AddItem(new Item("Axe", "O_CLASS_WEAPON", 5, "O_REQ_ONEHAND", 85, 10, 20));
            AddItem(new Item("Dagger", "O_CLASS_MIXEDWEAPON", 1, "O_REQ_ONEHAND", 88, 6, 10));
            AddItem(new Item("Bow", "O_CLASS_RANGEDWEAPON", 3, "O_REQ_TWOHANDS", 83, 9, 20));
            AddItem(new Item("Crossbow", "O_CLASS_RANGEDWEAPON", 4, "O_REQ_TWOHANDS", 82, 12, 20));
            AddItem(new Item("Throwing star", "O_CLASS_THROWINGWEAPON", 1, "O_REQ_ONEHAND", 89, 9, 5));
            AddItem(new Item("Fireblade", "O_CLASS_SPECIAL", 2, "O_REQ_ONEHAND", 173, 0, 150));
            AddItem(new Item("Helmet", "O_CLASS_ARMOR", 3, "O_REQ_HEAD", 91, 2, 20));
            AddItem(new Item("Shield", "O_CLASS_ARMOR", 3, "O_REQ_ONEHAND", 78, 4, 20));
            AddItem(new Item("Leather", "O_CLASS_ARMOR", 3, "O_REQ_BODY", 79, 2, 20));
            AddItem(new Item("Armour", "O_CLASS_ARMOR", 7, "O_REQ_BODY", 80, 6, 75));
            AddItem(new Item("Emerald", "O_CLASS_GADGET", 1, "O_REQ_NECK", 81, 0, 100));
            AddItem(new Item("Emerald ring", "O_CLASS_GADGET", 0, "O_REQ_FINGER", 90, 0, 150));
            AddItem(new Item("Arrows", "O_CLASS_ARROWS", 0, "O_REQ_NOTHING", 84, 0, 10));
            AddItem(new Item("Studded leather", "O_CLASS_ARMOR", 4, "O_REQ_BODY", 77, 3, 20));
            AddItem(new Item("Lightning bolt", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 55, 10, 0));
            AddItem(new Item("FireBall", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 60, 5, 0));
            AddItem(new Item("Portal", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 56, 7, 0));
            AddItem(new Item("Air", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 72, 7, 0));
            AddItem(new Item("Fire", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 70, 10, 0));
            AddItem(new Item("Water", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 68, 8, 0));
            AddItem(new Item("Water", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 68, 8, 0));
            AddItem(new Item("Earth", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 67, 8, 0));
            AddItem(new Item("Skeleton", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 64, 15, 0));
            AddItem(new Item("Zombie", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 65, 15, 0));
            AddItem(new Item("Vision", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 69, 2, 0));
            AddItem(new Item("Phantom", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 73, 3, 0));
            AddItem(new Item("Slayer", "O_CLASS_WEAPON", 8, "O_REQ_TWOHANDS", 122, 17, 150));
            AddItem(new Item("FastFeet", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 54, 8, 0));
            AddItem(new Item("Heal", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 53, 5, 20));
            AddItem(new Item("StoneAxe", "O_CLASS_WEAPON", 10, "O_REQ_TWOHANDS", 107, 15, 0));
            AddItem(new Item("Gloves", "O_CLASS_ARMOR", 1, "O_REQ_HANDS", 58, 1, 20));
            AddItem(new Item("Darkness", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 57, 10, 0));
            AddItem(new Item("Darkness", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 57, 10, 0));
            AddItem(new Item("Sabre", "O_CLASS_WEAPON", 7, "O_REQ_ONEHAND", 86, 10, 0));
            AddItem(new Item("Staff", "O_CLASS_WEAPON", 3, "O_REQ_TWOHANDS", 87, 8, 20));
            AddItem(new Item("Chaos", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 66, 20, 0));
            AddItem(new Item("Demon", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 63, 25, 0));
            AddItem(new Item("Cloak", "O_CLASS_ARMOR", 1, "O_REQ_SHOULDERS", 94, 1, 20));
            AddItem(new Item("Big shield", "O_CLASS_ARMOR", 6, "O_REQ_ONEHAND", 110, 6, 20));
            AddItem(new Item("Big helmet", "O_CLASS_ARMOR", 4, "O_REQ_HEAD", 111, 3, 20));
            AddItem(new Item("Opal ring", "O_CLASS_GADGET", 0, "O_REQ_FINGER", 97, 0, 150));
            AddItem(new Item("Club", "O_CLASS_WEAPON", 5, "O_REQ_ONEHAND", 119, 11, 20));
            AddItem(new Item("Topaz", "O_CLASS_GADGET", 1, "O_REQ_NECK", 123, 0, 300));
            AddItem(new Item("Opal", "O_CLASS_GADGET", 1, "O_REQ_NECK", 124, 0, 150));
            AddItem(new Item("Stonefoot", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 129, 6, 0));
            AddItem(new Item("Lightning", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 71, 15, 0));
            AddItem(new Item("DragonTooth", "O_CLASS_WEAPON", 4, "O_REQ_ONEHAND", 132, 13, 150));
            AddItem(new Item("Sun's Edge", "O_CLASS_WEAPON", 5, "O_REQ_ONEHAND", 133, 13, 150));
            AddItem(new Item("SilverBow", "O_CLASS_RANGEDWEAPON", 3, "O_REQ_TWOHANDS", 134, 11, 100));
            AddItem(new Item("Bubble", "O_CLASS_TRINKET", 0, "O_REQ_NOTHING", 92, 0, 150));
            AddItem(new Item("Faithful", "O_CLASS_ARROWS", 0, "O_REQ_NOTHING", 142, 0, 50));
            AddItem(new Item("SunBow", "O_CLASS_SPECIAL", 3, "O_REQ_TWOHANDS", 150, 11, 150));
            AddItem(new Item("Chock", "O_CLASS_SPECIAL", 4, "O_REQ_ONEHAND", 143, 2, 150));
            AddItem(new Item("BloodTaste", "O_CLASS_WEAPON", 9, "O_REQ_TWOHANDS", 144, 19, 200));
            AddItem(new Item("SunArmour", "O_CLASS_ARMOR", 4, "O_REQ_BODY", 149, 6, 150));
            AddItem(new Item("Elven cloak", "O_CLASS_ARMOR", 1, "O_REQ_SHOULDERS", 147, 3, 50));
            AddItem(new Item("Focus", "O_CLASS_GADGET", 1, "O_REQ_HANDS", 146, 0, 150));
            AddItem(new Item("Terror", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 153, 7, 0));
            AddItem(new Item("Berzerk", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 152, 3, 0));
            AddItem(new Item("Protection", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 151, 2, 0));
            AddItem(new Item("Leadball", "O_CLASS_THROWINGWEAPON", 1, "O_REQ_ONEHAND", 145, 8, 10));
            AddItem(new Item("Wooden shield", "O_CLASS_ARMOR", 2, "O_REQ_ONEHAND", 163, 3, 10));
            AddItem(new Item("Wakizashi", "O_CLASS_WEAPON", 2, "O_REQ_ONEHAND", 164, 9, 20));
            AddItem(new Item("SunHelmet", "O_CLASS_ARMOR", 2, "O_REQ_HEAD", 157, 3, 70));
            AddItem(new Item("SunShield", "O_CLASS_ARMOR", 3, "O_REQ_ONEHAND", 158, 6, 70));
            AddItem(new Item("ThunderStorm", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 159, 25, 0));
            AddItem(new Item("HyperSpace", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 160, 20, 0));
            AddItem(new Item("Panic", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 161, 20, 0));
            AddItem(new Item("Shooting star", "O_CLASS_SPECIAL", 0, "O_REQ_ONEHAND", 162, 0, 300));
            AddItem(new Item("Inferno", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 165, 12, 0));
            AddItem(new Item("Negator", "O_CLASS_TRINKET", 3, "O_REQ_NOTHING", 114, 0, 150));
            AddItem(new Item("Chain'n'ball", "O_CLASS_WEAPON", 5, "O_REQ_TWOHANDS", 170, 10, 0));
            AddItem(new Item("SunGloves", "O_CLASS_ARMOR", 1, "O_REQ_HANDS", 171, 2, 20));
            AddItem(new Item("Delay", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 172, 2, 0);
            AddItem(new Item("Ghostblade", "O_CLASS_SPECIAL", 4, "O_REQ_ONEHAND", 140, 9, 150));
            AddItem(new Item("Enchant", "O_CLASS_SPECIAL", 0, "O_REQ_ONEHAND", 178, 0, 100));
            AddItem(new Item("Purify", "O_CLASS_SPELL", 0, "O_REQ_ONEHAND", 179, 20, 0));
            AddItem(new Item("Blue", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Green", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Yellow", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Brown", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Red", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Grey", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("White", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Purple", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
            AddItem(new Item("Black", "O_CLASS_POTION", 1, "O_REQ_ONEHAND", 180, 0, 100));
        }

    }

}
